<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-I2TEE4P" failures="1" tests="1" name="Test" time="14.938" errors="0" timestamp="2022-11-02T14:05:04 IST">
  <testcase classname="com.testCases.TC_LoginDDT_002" name="loginDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at com.testCases.TC_LoginDDT_002.getData(TC_LoginDDT_002.java:66)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
</testsuite> <!-- Test -->
